/**
 * blogs-data.js — Dynamic Blog Registry
 *
 * Instead of hardcoded data, each category has its own articles.json
 * file at blogs/{domain}/articles.json, generated by the Python pipeline.
 *
 * articles.json entry shape:
 * {
 *   id: "blogs/ml/what-is-machine-learning.md",   ← relative path (also used as file)
 *   category: "ml",
 *   title: "...",
 *   description: "...",
 *   date: "YYYY-MM-DD",
 *   tags: ["tag1", "tag2"],
 *   readTime: "8 min",
 *   file: "blogs/ml/what-is-machine-learning.md"
 * }
 */

/* ── Category Metadata ─────────────────────────────────── */
const CATEGORY_META = {
  ml: {
    label: 'Machine Learning',
    shortLabel: 'ML',
    description: 'Algorithms, theory, and applied ML from fundamentals to production.',
    icon: '🧠',
    color: '#7c6af7',
    bgColor: 'rgba(124, 106, 247, 0.12)',
  },
  dl: {
    label: 'Deep Learning',
    shortLabel: 'DL',
    description: 'Neural networks, architectures, training tricks, and modern DL research.',
    icon: '🔬',
    color: '#4fc8b8',
    bgColor: 'rgba(79, 200, 184, 0.12)',
  },
  nlp: {
    label: 'Natural Language Processing',
    shortLabel: 'NLP',
    description: 'Text processing, transformers, LLMs, and language understanding.',
    icon: '📝',
    color: '#e879a0',
    bgColor: 'rgba(232, 121, 160, 0.12)',
  },
  cv: {
    label: 'Computer Vision',
    shortLabel: 'CV',
    description: 'Image processing, object detection, segmentation, and visual AI.',
    icon: '👁️',
    color: '#f59e0b',
    bgColor: 'rgba(245, 158, 11, 0.12)',
  },
  genai: {
    label: 'Generative AI',
    shortLabel: 'Gen AI',
    description: 'Diffusion models, LLMs, RAG, agents, and the frontier of AI generation.',
    icon: '✨',
    color: '#a78bfa',
    bgColor: 'rgba(167, 139, 250, 0.12)',
  },
  ainews: {
    label: 'AI News',
    shortLabel: 'AI News',
    description: 'Breaking developments, model releases, and industry analysis.',
    icon: '📡',
    color: '#34d399',
    bgColor: 'rgba(52, 211, 153, 0.12)',
  },
  statistics: {
    label: 'Statistics for AI',
    shortLabel: 'Stats',
    description: 'Probability, statistical tests, distributions, and the math behind ML.',
    icon: '📊',
    color: '#fb923c',
    bgColor: 'rgba(251, 146, 60, 0.12)',
  },
};

const ALL_CATEGORIES = ['ml', 'dl', 'nlp', 'cv', 'genai', 'ainews', 'statistics'];

/* ── Cache ─────────────────────────────────────────────── */
const _cache = {};

const R2_PUBLIC_URL = (typeof window !== 'undefined' && window.CONFIG && window.CONFIG.R2_PUBLIC_URL)
  ? window.CONFIG.R2_PUBLIC_URL
  : 'https://missing-config-js.r2.dev';

/* ── Core Fetch ────────────────────────────────────────── */
/**
 * Load articles.json from the Cloudflare R2 bucket.
 * Returns [] if the request fails (i.e. empty category).
 */
async function loadCategoryArticles(cat) {
  if (_cache[cat] !== undefined) return _cache[cat];

  try {
    const res = await fetch(`${R2_PUBLIC_URL}/blogs/${cat}/articles.json`);
    if (!res.ok) {
      _cache[cat] = [];
      return [];
    }
    const data = await res.json();
    _cache[cat] = Array.isArray(data) ? data : [];
    return _cache[cat];
  } catch (_) {
    _cache[cat] = [];
    return [];
  }
}

/**
 * Get articles for a category, sorted by sort order.
 * @param {string} cat  - category key
 * @param {string} sort - 'newest' | 'oldest'
 */
async function getBlogsByCategory(cat, sort = 'newest') {
  const articles = await loadCategoryArticles(cat);
  const sorted = [...articles].sort((a, b) =>
    sort === 'newest'
      ? new Date(b.date) - new Date(a.date)
      : new Date(a.date) - new Date(b.date)
  );
  return sorted;
}

/**
 * Get a single blog metadata by its id.
 * The id is generally the relative path "blogs/domain/slug.md" stored in the json.
 */
async function getBlogById(id) {
  // Try to parse category from path "blogs/{cat}/..."
  const parts = id.split('/');
  if (parts.length >= 3) {
    const cat = parts[1];
    if (CATEGORY_META[cat]) {
      const articles = await loadCategoryArticles(cat);
      const found = articles.find(a => a.id === id || a.file === id);
      if (found) return found;
    }
  }

  // Fallback brute force
  for (const cat of Object.keys(CATEGORY_META)) {
    const articles = await loadCategoryArticles(cat);
    const found = articles.find(a => a.id === id || a.file === id);
    if (found) return found;
  }
  return null;
}

/**
 * Get the N most recent articles across all main categories.
 */
async function getRecentBlogs(n = 6) {
  const all = await Promise.all(ALL_CATEGORIES.map(loadCategoryArticles));
  const flat = all.flat();
  flat.sort((a, b) => new Date(b.date) - new Date(a.date));
  return flat.slice(0, n);
}

/**
 * Get total article count across all categories.
 */
async function getTotalCount() {
  const all = await Promise.all(ALL_CATEGORIES.map(loadCategoryArticles));
  return all.reduce((sum, arr) => sum + arr.length, 0);
}

/* ── Formatting ─────────────────────────────────────────── */
function formatDate(dateStr) {
  if (!dateStr) return '';
  const [y, m, d] = dateStr.split('-').map(Number);
  return new Date(y, m - 1, d).toLocaleDateString('en-US', {
    year: 'numeric', month: 'long', day: 'numeric',
  });
}
